CREATE DATABASE IF NOT EXISTS gabi_crud;

USE gabi_crud;

CREATE TABLE amigos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(100)
)